project:
  type: website
  output-dir: _site

website:
  title: "MathZorro Blog"  # Text in top left corner
  navbar:
    background: "#222222"  # You can change this hex color to match your site
    foreground: "white"    # Text color
    search: true           # Enables the search magnifying glass
    
    # "left" items appear next to the title
    left:
      - text: "Main Site"
        href: https://mathzorro.github.io/
      
      # A drop-down menu for your Blog Categories
      - text: "Blog Categories"
        menu:
          - text: "All Posts"
            href: index.qmd
          - text: "Math"
            href: math.qmd
          - text: "Art"
            href: art.qmd
          - text: "Misc"
            href: misc.qmd

    # "right" items appear on the far right side
    right:
      - text: "Research"
        href: https://hanusa.xyz/research.html
      - text: "Teaching"
        href: https://hanusa.xyz/teaching.html
      - text: "Artworks"
        href: https://mathzorro.github.io/art.html
      - icon: github
        href: https://github.com/mathzorro
