project:
  type: website
  output-dir: _site

listing:
  contents: posts
  sort: "date desc"
  categories: true
  feed:
    type: metadata  # makes it so that the feed includes the metadata and not the full posts. 
    categories:     
      - "math"
      - "art"  
      - "teaching"
      - "admin"
      - "misc"
      
website:
  title: "Insights by Christopher R. H. Hanusa"
  site-url: "https://hanusa.xyz/blog"  # <--- This is required for RSS
  description: "Writings by Christopher R. H. Hanusa about math, art, coding, teaching, leadership, academia, and other miscellaneous topics"
  
  search:
    location: sidebar
    type: textbox
    
  navbar:
    title: false
    logo: "hanusa-xyz.png"       
    logo-href: https://hanusa.xyz 
    background: "white"  
    foreground: "#777777"    # Text color

    left:
     - text: "Insights"
       href: https://hanusa.xyz/blog/

    # "right" items appear on the far right side
    right:
      - text: "Research"
        href: https://hanusa.xyz/research.html
      - text: "Design"
        href: https://hanusa.xyz/design.html
      - text: "Education"
        href: https://hanusa.xyz/education.html
      - text: "Strategy"
        href: https://hanusa.xyz/strategy.html
      - text: "Insights"
        href: https://hanusa.xyz/blog/
      - text: "Contact"
        href: https://hanusa.xyz/contact.html

  sidebar:
    search: true
    contents:
      - text: "All posts"     # <--- This creates the link below search
        href: index.qmd              
format:
  html:
    toc: true          
    toc-location: left 
    toc-title: "Contents" # Fallback if title is missing
    css: blog_styles.css  
